export const IG_URL =
    "https://graph.instagram.com/me/media?fields=media_type,media_url,username,timestamp,permalink&access_token=";
export const IG_KEY =
    "IGQWRPUVcwTkJYUWM4TnBuMnhFWjRUQ2ZALV1NEemZAfc09Vb0dyWkw2WFVjZAXV0S2FDYlJMYWxVNU85bmpaei1ZAQ1BCNUlkdUJTakstN2hpWTVWUUlXYzlibVJEandGUzZAxbGZA4TDRwdHRVSmlZANGVfcWV2Y090SkkZD";

// "IGQWRPUm1oMDh3VnZAoa0dGS2VqN0hTdllRQThVckJLajRrMUh4TGh2LUVlNl90cFpsMnNiMkhOeWpVOGMwSWwzX3RjTURjdE96UHpxVjU1aWptTkFsQ1RKbEI0TVNVazNwY0VTM25pRkw2Vl83SVpYa0VtbVNQbFEZD";
